### ISSUE TITLE
404 on both magento and sample data

### ISSUE THREAD

**Issue by pquerner** [klierik/simple-magento-vagrant#2]
Might use this source for the sample data
https://github.com/Vinai/compressed-magento-sample-data

and for the original magento I'm sure theres a github repo around somewhere we could use?

**Comment by klierik** [comment]
i'm not sure that i understand what you are talking about.
can you describe more info please

**Comment by pquerner** [comment]
The .sh file is using a link for both the sample data and magento which returns a http code 404.

**Comment by klierik** [comment]
added update for Magento and Sample data, merged into master/
