### ISSUE TITLE
bootstrap.sh file references "Magento 2"

### ISSUE THREAD

**Issue by pquerner** [klierik/simple-magento-vagrant#3]
https://github.com/klierik/simple-magento-vagrant/blob/master/vagrant/bootstrap.sh#L7

Shouldnt be the case, no?

**Comment by klierik** [comment]
Magento1 and Magento2 project based on the same sample.
This is the comment only, there is no any problem here

**Comment by pquerner** [comment]
This script downloads and extracts magento v1 and it references v2 in a comment.

**Comment by klierik** [comment]
comment updated, merged into master/
