### ISSUE TITLE
Magento is very slow

### ISSUE THREAD

**Issue by sivajik34** [klierik/simple-magento-vagrant#5]
I Installed Virtual box,vagrant in Windows 10,Ram :4 Gb,Intel core i3-5015U cpu @ 2.10 Ghz processor.
And I followed Your repo & installed magento.
But its very slow.Is there any way to increase site speed?
Thanks in advance.

**Comment by klierik** [comment]
There is not Ram/CPU problem... The main problem with Read/Write issue because of a lot if files.
You can try:
- Use NFS feature: https://www.vagrantup.com/docs/synced-folders/nfs.html
- You can you VMWare (but you need buy Provider https://www.vagrantup.com/vmware/ ). I use this way and it really fast on my laptop (MBP 2015/16GB RAM)

**Comment by sivajik34** [comment]
There is a message In the above link:
Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.
So I installed following tool for this.
https://github.com/winnfsd/vagrant-winnfsd
After that I modified vagrant file like this:
config.vm.synced_folder ".", "/vagrant", type: "nfs".
then I ran vagrant reload command.Its successfully completed.
but when i goto my  browser from my host nothing is coming.
If i create index.php file with some echos in guest machine.its displaying those messages.
Can you help me on this?
I think files not taking from host machine?
![index of](https://cloud.githubusercontent.com/assets/7636894/18659873/edf4951e-7f2a-11e6-9c47-1a82c578609f.png)

**Comment by klierik** [comment]
try this:
`config.vm.synced_folder "d:/path-to-your-project-folder/", "/vagrant/httpdocs", nfs: true`

**Comment by sivajik34** [comment]
Still i'm facing same issue.

config.vm.synced_folder "C:/vm/m92/simple-magento-vagrant/magento", "/vagrant/httpdocs", nfs: true

C:\vm\m92\simple-magento-vagrant\vagrant>vagrant reload
==> simple-magento-vagrant: Attempting graceful shutdown of VM...
==> simple-magento-vagrant: Clearing any previously set forwarded ports...
==> simple-magento-vagrant: Clearing any previously set network interfaces...
==> simple-magento-vagrant: Preparing network interfaces based on configuration...
    simple-magento-vagrant: Adapter 1: nat
    simple-magento-vagrant: Adapter 2: hostonly
    simple-magento-vagrant: Adapter 3: hostonly
==> simple-magento-vagrant: Forwarding ports...
    simple-magento-vagrant: 80 (guest) => 8999 (host) (adapter 1)
    simple-magento-vagrant: 22 (guest) => 2299 (host) (adapter 1)
    simple-magento-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> simple-magento-vagrant: Running 'pre-boot' VM customizations...
==> simple-magento-vagrant: Booting VM...
==> simple-magento-vagrant: Waiting for machine to boot. This may take a few minutes...
    simple-magento-vagrant: SSH address: 127.0.0.1:2222
    simple-magento-vagrant: SSH username: vagrant
    simple-magento-vagrant: SSH auth method: private key
==> simple-magento-vagrant: Machine booted and ready!
==> simple-magento-vagrant: Checking for guest additions in VM...
    simple-magento-vagrant: The guest additions on this VM do not match the installed version of
    simple-magento-vagrant: VirtualBox! In most cases this is fine, but in rare cases it can
    simple-magento-vagrant: prevent things such as shared folders from working properly. If you see
    simple-magento-vagrant: shared folder errors, please make sure the guest additions within the
    simple-magento-vagrant: virtual machine match the version of VirtualBox you have installed on
    simple-magento-vagrant: your host and reload your VM.
    simple-magento-vagrant:
    simple-magento-vagrant: Guest Additions Version: 4.3.36
    simple-magento-vagrant: VirtualBox Version: 5.1
==> simple-magento-vagrant: Setting hostname...
==> simple-magento-vagrant: Configuring and enabling network interfaces...
==> simple-magento-vagrant: Exporting NFS shared folders...
==> simple-magento-vagrant: Preparing to edit nfs mounting file.
[NFS] Status: running
==> simple-magento-vagrant: Mounting NFS shared folders...
==> simple-magento-vagrant: Mounting shared folders...
    simple-magento-vagrant: /vagrant => C:/vm/m92/simple-magento-vagrant/vagrant
==> simple-magento-vagrant: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> simple-magento-vagrant: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by klierik** [comment]
have you done this?

``` ruby
# A private dhcp network is required for NFS to work (on Windows hosts, at least)
config.vm.network "private_network", type: "dhcp"
```

**Comment by sivajik34** [comment]
yes.

```

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    # config.vm.box = "precise64"
    # config.vm.box = "precise32"
    config.vm.box = "trusty64"

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    # config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    # config.vm.box_url = "http://files.vagrantup.com/precise32.box"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Provision
    config.vm.provision :shell, :path => "bootstrap.sh"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network :forwarded_port, guest: 80, host: 8999
    config.vm.network :forwarded_port, guest: 22, host: 2299


    # Synced folder
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs"
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs",type: "nfs"
    config.vm.synced_folder "C:/vm/m92/simple-magento-vagrant/magento", "/vagrant/httpdocs", nfs: true
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", nfs: true, mount_options: ["nolock", "async"], bsd__nfs_options: ["alldirs","async","nolock"]
    # config.nfs.map_uid = 0
    # config.nfs.map_gid = 0

    # A private dhcp network is required for NFS to work (on Windows hosts, at least)
      config.vm.network "private_network", type: "dhcp"

    # VirtualBox settings
    config.vm.provider :virtualbox do |vb|
        # vb.customize ["modifyvm", :id, "--memory", "512"]
        # vb.customize ["modifyvm", :id, "--memory", "1024"]
        # vb.customize ["modifyvm", :id, "--memory", "2048"]
        # vb.customize ["modifyvm", :id, "--memory", "3072"]
        # vb.customize ["modifyvm", :id, "--memory", "4096"]
    end


    # VirtualBox setting
    # Use all CPU cores and 1/4 system memory
    config.vm.provider "virtualbox" do |v|
        host = RbConfig::CONFIG['host_os']

        # Give VM 1/8 system memory & access to all cpu cores on the host
        if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 8
        elsif host =~ /linux/
            cpus = `nproc`.to_i
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 8
        else # sorry Windows folks, I can't help you
            cpus = 2
            mem = 1024
        end

        v.customize ["modifyvm", :id, "--memory", mem]
        v.customize ["modifyvm", :id, "--cpus", cpus]
    end


    # Host Manager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'simple-magento-vagrant' do |node|
        node.vm.hostname = 'simple-magento-vagrant'
        node.vm.network :private_network, ip: '192.168.99.99'
        node.hostmanager.aliases = %w(simple-magento-vagrant.dev)
    end
end
```

**Comment by klierik** [comment]
i suppose you need you dhcp for hostmanager settings:
`node.vm.network :private_network, type: "dhcp"`

**Comment by sivajik34** [comment]
So instead of `node.vm.network :private_network, ip: '192.168.99.99'`  i need to place `node.vm.network :private_network, type: "dhcp"` ?
Otherwise both need to be there?

**Comment by klierik** [comment]
try this config

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    # config.vm.box = "precise64"
    # config.vm.box = "precise32"
    config.vm.box = "trusty64"

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    # config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    # config.vm.box_url = "http://files.vagrantup.com/precise32.box"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Provision
    config.vm.provision :shell, :path => "bootstrap.sh"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network :forwarded_port, guest: 80, host: 8999
    config.vm.network :forwarded_port, guest: 22, host: 2299


    # Synced folder
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs"
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs",type: "nfs"
    config.vm.synced_folder "C:/vm/m92/simple-magento-vagrant/magento", "/vagrant/httpdocs", nfs: true
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", nfs: true, mount_options: ["nolock", "async"], bsd__nfs_options: ["alldirs","async","nolock"]
    # config.nfs.map_uid = 0
    # config.nfs.map_gid = 0

    # VirtualBox settings
    config.vm.provider :virtualbox do |vb|
        # vb.customize ["modifyvm", :id, "--memory", "512"]
        # vb.customize ["modifyvm", :id, "--memory", "1024"]
        # vb.customize ["modifyvm", :id, "--memory", "2048"]
        # vb.customize ["modifyvm", :id, "--memory", "3072"]
        # vb.customize ["modifyvm", :id, "--memory", "4096"]
    end


    # VirtualBox setting
    # Use all CPU cores and 1/4 system memory
    config.vm.provider "virtualbox" do |v|
        host = RbConfig::CONFIG['host_os']

        # Give VM 1/8 system memory & access to all cpu cores on the host
        if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 8
        elsif host =~ /linux/
            cpus = `nproc`.to_i
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 8
        else # sorry Windows folks, I can't help you
            cpus = 1
            mem = 1024
        end

        v.customize ["modifyvm", :id, "--memory", mem]
        v.customize ["modifyvm", :id, "--cpus", cpus]
    end


    # Host Manager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'simple-magento-vagrant' do |node|
        node.vm.hostname = 'simple-magento-vagrant'
        node.vm.network :private_network, type: "dhcp"
        node.hostmanager.aliases = %w(simple-magento-vagrant.dev)
    end
end
```

also i changed `cpus = 2` to `cpus = 1` because your CPU has 2 cores.

**Comment by sivajik34** [comment]
`this site cannot be reached`  message is coming.

**Comment by klierik** [comment]
can you show me result of `$ vagrant plugin list` command, example:

```
$ vagrant plugin list
vagrant-bindfs (0.4.9)
vagrant-hostmanager (1.8.2)
vagrant-share (1.1.5, system)
vagrant-vmware-fusion (4.0.10)
```

**Comment by sivajik34** [comment]
I removed vagrant file and i created freshly.
vagrant-hostmanager (1.8.5)
vagrant-share (1.1.5, system)
vagrant-winnfsd (1.3.0)

C:\vm\simple-magento-vagrant\vagrant>vagrant reload
==> simple-magento-vagrant: Attempting graceful shutdown of VM...
==> simple-magento-vagrant: Clearing any previously set forwarded ports...
==> simple-magento-vagrant: Clearing any previously set network interfaces...
==> simple-magento-vagrant: Preparing network interfaces based on configuration...
    simple-magento-vagrant: Adapter 1: nat
    simple-magento-vagrant: Adapter 2: hostonly
==> simple-magento-vagrant: Forwarding ports...
    simple-magento-vagrant: 80 (guest) => 8999 (host) (adapter 1)
    simple-magento-vagrant: 22 (guest) => 2299 (host) (adapter 1)
    simple-magento-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> simple-magento-vagrant: Running 'pre-boot' VM customizations...
==> simple-magento-vagrant: Booting VM...
==> simple-magento-vagrant: Waiting for machine to boot. This may take a few minutes...
    simple-magento-vagrant: SSH address: 127.0.0.1:2222
    simple-magento-vagrant: SSH username: vagrant
    simple-magento-vagrant: SSH auth method: private key
==> simple-magento-vagrant: Machine booted and ready!
==> simple-magento-vagrant: Checking for guest additions in VM...
    simple-magento-vagrant: The guest additions on this VM do not match the installed version of
    simple-magento-vagrant: VirtualBox! In most cases this is fine, but in rare cases it can
    simple-magento-vagrant: prevent things such as shared folders from working properly. If you see
    simple-magento-vagrant: shared folder errors, please make sure the guest additions within the
    simple-magento-vagrant: virtual machine match the version of VirtualBox you have installed on
    simple-magento-vagrant: your host and reload your VM.
    simple-magento-vagrant:
    simple-magento-vagrant: Guest Additions Version: 4.3.36
    simple-magento-vagrant: VirtualBox Version: 5.1
==> simple-magento-vagrant: Setting hostname...
==> simple-magento-vagrant: Configuring and enabling network interfaces...
==> simple-magento-vagrant: Exporting NFS shared folders...
==> simple-magento-vagrant: Preparing to edit nfs mounting file.
[NFS] Status: halted
[NFS] Start: started
==> simple-magento-vagrant: Mounting NFS shared folders...
==> simple-magento-vagrant: Mounting shared folders...
    simple-magento-vagrant: /vagrant => C:/vm/simple-magento-vagrant/vagrant
==> simple-magento-vagrant: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> simple-magento-vagrant: flag to force provisioning. Provisioners marked to run always will still run

**Comment by klierik** [comment]
hm... okay, moving to next one...

Go to `C:/vm/m92/simple-magento-vagrant/vagrant/` and run `$ vagrant hostmanager`
Then try again open Magento in browser. If no success then...

show what you have in `C:\Windows\System32\drivers\etc\hosts` file

Also go to `C:/vm/m92/simple-magento-vagrant/vagrant/` folder and run `$ vagrant ssh` command.
When you enter into Guest OS run:

```
$ cd /vagrant/httpdocs
$ ls -la
```

And paste here command result.

**Comment by sivajik34** [comment]
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#   127.0.0.1       localhost
#   ::1             localhost

## vagrant-hostmanager-start id: fb183b4d-6467-4317-a9b0-9de26afd88bb
127.0.0.1   simple-magento-vagrant
127.0.0.1   simple-magento-vagrant.dev
## vagrant-hostmanager-end
```

vagrant@simple-magento-vagrant:/vagrant/httpdocs$ ls -la
total 11337
drwxrwxrwx 1 vagrant vagrant     8192 Sep 20 08:21 .
drwxrwxrwx 1 vagrant vagrant     4096 Sep 20 08:06 ..
drwxrwxrwx 1 vagrant vagrant        0 Sep 20 08:05 adminer
-rwxrwxrwx 1 vagrant vagrant     3141 Sep 20 08:15 api.php
drwxrwxrwx 1 vagrant vagrant     4096 Jan 21  2016 app
-rwxrwxrwx 1 vagrant vagrant     2915 Sep 20 08:18 cron.php
-rwxrwxrwx 1 vagrant vagrant     1639 Sep 20 08:18 cron.sh
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 dev
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 downloader
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 errors
-rwxrwxrwx 1 vagrant vagrant     1150 Sep 20 08:19 favicon.ico
-rwxrwxrwx 1 vagrant vagrant     5970 Sep 20 08:19 get.php
-rwxrwxrwx 1 vagrant vagrant       19 Sep 20 08:15 .gitignore
-rwxrwxrwx 1 vagrant vagrant     6451 Sep 20 08:15 .htaccess
-rwxrwxrwx 1 vagrant vagrant     5351 Sep 20 08:15 .htaccess.sample
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 includes
-rwxrwxrwx 1 vagrant vagrant     2614 Sep 20 08:19 index.php
-rwxrwxrwx 1 vagrant vagrant     2323 Sep 20 08:19 index.php.sample
-rwxrwxrwx 1 vagrant vagrant     6460 Sep 20 08:19 install.php
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 js
-rwxrwxrwx 1 vagrant vagrant        0 Aug 16 07:55 .keep
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 lib
-rwxrwxrwx 1 vagrant vagrant    10421 Sep 20 08:15 LICENSE_AFL.txt
-rwxrwxrwx 1 vagrant vagrant    10679 Sep 20 08:15 LICENSE.html
-rwxrwxrwx 1 vagrant vagrant    10410 Sep 20 08:15 LICENSE.txt
-rwxrwxrwx 1 vagrant vagrant     2240 Sep 20 08:20 mage
-rwxrwxrwx 1 vagrant vagrant 10925815 Sep 20 08:21 magento_sample_data_for_1.9.1                                                                                        .0.sql
drwxrwxrwx 1 vagrant vagrant        0 Nov 24  2014 media
-rwxrwxrwx 1 vagrant vagrant      886 Sep 20 08:20 php.ini.sample
-rwxrwxrwx 1 vagrant vagrant   589049 Sep 20 08:15 RELEASE_NOTES.txt
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 shell
drwxrwxrwx 1 vagrant vagrant        0 Nov 24  2014 skin
drwxrwxrwx 1 vagrant vagrant        0 Jan 21  2016 var

**Comment by klierik** [comment]
try remove next block in hosts

```
## vagrant-hostmanager-start id: fb183b4d-6467-4317-a9b0-9de26afd88bb
127.0.0.1   simple-magento-vagrant
127.0.0.1   simple-magento-vagrant.dev
## vagrant-hostmanager-end
```

and after that run in `C:/vm/m92/simple-magento-vagrant/vagrant/` command `$ vagrant hostmanager`

Open new Private Window in browser and go http://simple-magento-vagrant.dev

**Comment by sivajik34** [comment]
I did what u said above.but still same issue.also hosts file updated with same entry.

**Comment by klierik** [comment]
okay, let's check that Magento work w/o NFS. Disable it and reload Vagrant.
Is Magento open in browser?

**Comment by sivajik34** [comment]
No.still same issue only.something i missed.Before Its working fine without NFS.

**Comment by klierik** [comment]
hm... try remove all changes, but leave `node.vm.network :private_network, type: "dhcp"` row, run hostmanager and try again

**Comment by sivajik34** [comment]
==> simple-magento-vagrant: Attempting graceful shutdown of VM...
    simple-magento-vagrant: Guest communication could not be established! This is usually because
    simple-magento-vagrant: SSH is not running, the authentication information was changed,
    simple-magento-vagrant: or some other networking issue. Vagrant will force halt, if
    simple-magento-vagrant: capable.
==> simple-magento-vagrant: Forcing shutdown of VM...
==> simple-magento-vagrant: Clearing any previously set forwarded ports...
==> simple-magento-vagrant: Clearing any previously set network interfaces...
==> simple-magento-vagrant: Preparing network interfaces based on configuration...
    simple-magento-vagrant: Adapter 1: nat
    simple-magento-vagrant: Adapter 2: hostonly
==> simple-magento-vagrant: Forwarding ports...
    simple-magento-vagrant: 80 (guest) => 8999 (host) (adapter 1)
    simple-magento-vagrant: 22 (guest) => 2299 (host) (adapter 1)
    simple-magento-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> simple-magento-vagrant: Running 'pre-boot' VM customizations...
==> simple-magento-vagrant: Booting VM...
==> simple-magento-vagrant: Waiting for machine to boot. This may take a few minutes...
    simple-magento-vagrant: SSH address: 127.0.0.1:2222
    simple-magento-vagrant: SSH username: vagrant
    simple-magento-vagrant: SSH auth method: private key
==> simple-magento-vagrant: Machine booted and ready!
==> simple-magento-vagrant: Checking for guest additions in VM...
    simple-magento-vagrant: The guest additions on this VM do not match the installed version of
    simple-magento-vagrant: VirtualBox! In most cases this is fine, but in rare cases it can
    simple-magento-vagrant: prevent things such as shared folders from working properly. If you see
    simple-magento-vagrant: shared folder errors, please make sure the guest additions within the
    simple-magento-vagrant: virtual machine match the version of VirtualBox you have installed on
    simple-magento-vagrant: your host and reload your VM.
    simple-magento-vagrant:
    simple-magento-vagrant: Guest Additions Version: 4.3.36
    simple-magento-vagrant: VirtualBox Version: 5.1
==> simple-magento-vagrant: Setting hostname...
==> simple-magento-vagrant: Configuring and enabling network interfaces...
==> simple-magento-vagrant: Mounting shared folders...
    simple-magento-vagrant: /vagrant => C:/vm/simple-magento-vagrant/vagrant
    simple-magento-vagrant: /vagrant/httpdocs => C:/vm/simple-magento-vagrant/magento
==> simple-magento-vagrant: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> simple-magento-vagrant: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by klierik** [comment]
let's try re-create VM with current settings

```
$ vagrant destroy -f
$ vagrant up
```
