### ISSUE TITLE
vagrant up does not work - need permission

### ISSUE THREAD

**Issue by TheSearcher** [klierik/simple-magento-vagrant#6]
hi

i am on windows 8

i did a vagrant up  but got a message below. i would appriciate any advice on how to resolve it.

 to (C:/Windows/system32/drivers/etc/hosts)
==> simple-magento-vagrant: [vagrant-hostsupdater]   192.168.99.99  simple-magen                                                                                                                to-vagrant  # VAGRANT: 249c1555c7369919572234f3772a634a (simple-magento-vagrant)                                                                                                                 / 177a770d-f61a-4481-8c8f-fed3bf7dbc48
==> simple-magento-vagrant: [vagrant-hostsupdater] This operation requires admin                                                                                                                istrative access. You may skip it by manually adding equivalent entries to the h                                                                                                                osts file.
==> simple-magento-vagrant: Forcing shutdown of VM...
==> simple-magento-vagrant: Destroying VM and associated drives...
C:/Users/endy/.vagrant.d/gems/2.2.5/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-                                                                                                                hostsupdater/HostsUpdater.rb:98:in `initialize': Permission denied @ rb_sysopen                                                                                                                 - C:/Windows/system32/drivers/etc/hosts (Errno::EACCES)
        from C:/Users/endy/.vagrant.d/gems/2.2.5/gems/vagrant-hostsupdater-1.0.2                                                                                                                /lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `open'
        from C:/Users/endy/.vagrant.d/gems/2.2.5/gems/vagrant-hostsupdater-1.0.2                                                                                                                /lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `addToHosts'
        from C:/Users/endy/.vagrant.d/gems/2.2.5/gems/vagrant-hostsupdater-1.0.2                                                                                                                /lib/vagrant-hostsupdater/HostsUpdater.rb:47:in `addHostEntries'
        from C:/Users/endy/.vagrant.d/gems/2.2.5/gems/vagrant-hostsupdater-1.0.2                                                                                                                /lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/a                                                                                                                ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/a

**Comment by klierik** [comment]
@TheSearcher you should try run CMD with Admin permissions

**Comment by TheSearcher** [comment]
hi

i did it and it worked. thank you so much.

quick question. where do i go to change the version of the magneto. i want to install an earlier  version of magento

**Comment by klierik** [comment]
https://magento.com/tech-resources/download > "RELEASE ARCHIVE" Tab and scroll down to "ver 1.9.x"
